### WORKSPACES ###
exec-once = firefox                         # workspace 2 for firefox
exec-once = [workspace 5 silent] $terminal btop # btop on workspace 5
exec-once = [workspace 6 silent] armcord
exec-once = [workspace 7 silent] steam
